raw_pos_min:  [-4.0,]
raw_pos_max: [6.0,]
surface_pressure_mean: [-1.00952e-01]
surface_pressure_std: [1.88242e-01]
surface_friction_mean: [-1.52900e-03, 7.83792e-09, -5.82453e-05]
surface_friction_std: [1.17512e-03, 6.52266e-04, 7.13125e-04]
volume_velocity_mean: [8.74600e-01, 1.42877e-05, 7.76145e-03]
volume_velocity_std: [3.00305e-01, 1.14927e-01, 1.24698e-01]
volume_pressure_mean: [8.12013e-01]
volume_pressure_std: [3.67992e-01]
volume_vorticity_logscale_mean: [-1.45271e-04, 1.29314e-01, 1.29501e-05]
volume_vorticity_logscale_std: [1.11017e00, 1.96530e00, 1.77495e00]