raw_pos_min:  [-40.0,]
raw_pos_max: [80.0,]
surface_pressure_mean: [-2.29772e02,]
surface_pressure_std: [2.69345e02,]
surface_friction_mean: [-1.20054e00, 1.49358e-03, -7.20107e-02]
surface_friction_std: [2.07670e00, 1.35628e00, 1.11426e00]
volume_velocity_mean: [1.67909e01, -3.82238e-02, 4.07968e-01]
volume_velocity_std: [1.64115e01, 8.63614e00, 6.64996e00]
volume_pressure_mean: [1.71387e-01,]
volume_pressure_std: [5.00826e-01,]
volume_vorticity_logscale_mean: [-1.47814e-02, 7.87642e-01, 2.81023e-03]
volume_vorticity_logscale_std: [5.45681e00, 5.77081e00, 5.46175e00]