raw_pos_min:  [-12.01]
raw_pos_max: [6.41,]
surface_domain_min: [-1.15154e00, -1.19442e00, 0.00000e00]
surface_domain_max: [4.20453e00, 1.19442e00, 1.76205e00]
surface_pos_mean: [1.53702e00, -8.12572e-03, 5.93542e-01]
surface_pos_std: [1.39704e00, 6.44139e-01, 3.88172e-01]
surface_pressure_mean: [-9.34098e01]
surface_pressure_std: [1.20787e02]
surface_friction_mean: [-6.71649e-01, 3.63487e-02, -8.46379e-02]
surface_friction_std: [8.19941e-01, 4.51045e-01, 7.81055e-01]
volume_pos_mean: [2.17577e00, -3.35840e-01, 7.60331e-01]
volume_pos_std: [3.06283e00, 7.20275e-01, 6.50708e-01]
volume_pressure_mean: [-6.24053e01]
volume_pressure_std: [9.42394e01]
volume_velocity_mean: [2.18719e01, -2.37778e-01, 6.73902e-01]
volume_velocity_std: [1.21079e01, 3.97768e00, 3.90113e00]
volume_vorticity_mean: [2.24115e00, 3.02183e01, 2.58549e01]
volume_vorticity_std: [1.25151e05, 1.50186e05, 2.33779e05]
volume_vorticity_logscale_mean: [2.57623e-02, 2.58335e-01, 4.29835e-01]
volume_vorticity_logscale_std: [3.00179e00, 3.65020e00, 3.33356e00]
volume_vorticity_magnitude_mean: 3.03779e02
volume_vorticity_magnitude_std: 3.04748e05
volume_domain_min: [-1.20012e01, -4.00040e00, -3.46979e-18]
volume_domain_max: [3.20032e01, 4.00040e00, 6.40064e00]