
raw_pos_min:  [-17.5]
raw_pos_max: [17.5]

surface_pressure_mean: [92656.34610807039]
surface_pressure_std: [11929.058756240694]
surface_friction_mean: [-74.10092405045339,-0.5525946509854017,0.0401677695420727]
surface_friction_std: [47.16838501471528,10.233076648224564,23.08224849769229]
volume_velocity_mean: [187.92724405048926,0.5335961966484881,-0.0812512160659759]
volume_velocity_std: [83.6810800019851,19.911990565773156,33.3370080829507]
volume_pressure_mean: [93342.81261991762]
volume_pressure_std: [11743.515250769764]

volume_vorticity_logscale_mean: [-0.013138919851553849, 0.0033505699708222037, -1.6626923006758065]
volume_vorticity_logscale_std: [6.217698713293661,8.787798800793741,5.512463961862133]
volume_vorticity_magnitude_mean: 3.79027e+04

geometry_design_parameters_mean: [0.9495975525165955,1.2492765187383101,0.5500557258109463,19.92001709415523,0]
geometry_design_parameters_std: [0.14422534397647097,0.14465871522018967,0.08706049742886027,11.557458965186635,1]
inflow_design_parameters_mean: [224.59267997259747,-0.045877170231132774]
inflow_design_parameters_std: [43.25454930960363,5.792067554535914]