kind: tutorial.pipeline.AeroMultistagePipeline
num_surface_points: 3586 # max = 3586
num_volume_points: 4096   # max = 28504
num_surface_queries: 0
num_volume_queries: 0
use_physics_features: ${trainer.use_physics_features}
dataset_statistics: ${dataset_statistics}
data_specs: ${data_specs}