# @package _global_

collator_kind: boilerplate_project.pipelines.BaseMultiStagePipeline
dataset_kind: boilerplate_project.datasets.BaseDataset
config_schema_kind : boilerplate_project.schemas.config_schema.BoilerplateConfigSchema

defaults:
  - model: base_model
  - datasets: base_dataset
  - tracker: base_tracker
  - callbacks: base_callback
  - trainer: base_trainer
  - optim: adamw 
  - _self_

output_path: ./outputs