# @package _global_

# Define key values here that are used multiple times in the config files.
dataset_root:  <path to your ahmedml dataset root>
dataset_kind: noether.data.datasets.cfd.AhmedMLDataset

defaults:
  - train_caeml 
  - dataset_statistics: ahmedml_stats
