weight_decay: 1e-5
clip_grad_norm: 1.0
lr: 1.0e-3
schedule_config:
  kind: noether.core.schedules.LinearWarmupCosineDecaySchedule
  warmup_percent: 0.3
  end_value: 1.0e-6
  max_value: ${model.optimizer_config.lr}