- kind: noether.training.callbacks.OfflineLossCallback
  batch_size: 1
  every_n_epochs: 1
  dataset_key: test
  name: OfflineLossCallback
- kind: noether.core.callbacks.CheckpointCallback
  every_n_epochs: 1
  save_weights: false
  save_latest_weights: true
  save_latest_optim: true
  name: CheckpointCallback
- kind: boilerplate_project.callbacks.BaseCallback
  dataset_key: test
  every_n_epochs: 1
  batch_size: 1
  name: BaseCallback